name: 'Deversion'
description: 'Makes it possible to use NPM caching when versioning. Removes `version` from `package-lock.json`. Use it before the `actions/cache` step.'
author: 'Sergey N <mrauhu@yandex.ru> (https://mrauhu.ru)'
runs:
  using: 'node12'
  main: 'dist/index.js'
