name: 'build-test'
on: # rebuild any PRs and master branch changes
  pull_request:
  push:
    tags:
      - "v*"
    branches:
      - master
      - 'releases/*'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: ./github/actions/cache/checkout/
  install:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: ./github/actions/cache/
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: ./github/actions/cache/
      - run: npm run build
      - run: npm run package
      - run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: ./github/actions/cache/
      - run: npm test

  test-clean: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: ./github/actions/cache/checkout/
      - uses: ./
