name: 'build-test'
on: # rebuild any PRs and master branch changes
  pull_request:
  push:
    tags:
      - "v*"
    branches:
      - master
      - 'releases/*'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./github/actions/cache/install/
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: ./github/actions/cache/install/
      - run: npm run build
      - run: npm run package
      - run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: ./github/actions/cache/install/
      - run: npm test

  test-clean: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
